### ISSUE TITLE
docker image , execution halted

### ISSUE THREAD

**Issue by mlplace** [PavlopoulosLab/Flame#4]
When attempting to use the docker image, it fails:

docker run -p 3838:3838 -ti --rm pavlopouloslab/flame

R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> shiny::runApp('/root/Flame/')
Error in loadNamespace(x) : there is no package called ‘shiny’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

**Comment by fbaltoumas** [comment]
Hello,

Thank you for noticing this! The image in dockerhub was broken, for some reason.

I have re-built and re-pushed the image. Please **delete** the old broken version, pull the latest one and try again.

**Comment by mlplace** [comment]
Thank you for the speedy response.  I was able to run the docker image, no problems.  Thank you for this work.
